### ISSUE TITLE
[BUG] - Aircraft data sent is wrong for PHpvms 5.7

### ISSUE THREAD

**Issue by EpicHax7** [invernyx/smartcars-3-public-api#101] opened 2023-09-30 05:41 UTC
### Describe the bug

Hello we are currently based on vms v5.7 and use smart cars 3 as our acars 
the problem we face is it sends wrong or no data to our servers so sometimes in live flights aircraft is blank or it remains stuck on a single registration and aircraft for all the flights for eg if i flew QTR A7-BFB registration it wont change even if i flew a united aircraft 
please can we get support on this 
as Phpvms 5 is supported by you and mentioned in the requirements and no upgrading to vms7 is not possible for us now 
thank you 

### How do you reproduce this bug?

1.Live flights list on our VA 's website 
2-aircraft data wrong

### Expected behavior

it should change with change in flights (Registration and aircraft type)
ATTACHED  a screenshot where sc3 doesnt send any aircraft data 
but sc2 does

### Screenshots

![image](https://github.com/invernyx/smartcars-3-public-api/assets/117974892/48e9d84a-efe3-489d-afeb-dc77dee34625)
![image](https://github.com/invernyx/smartcars-3-public-api/assets/117974892/c89e9bf2-4880-4be0-b37f-635595331b94)
![image](https://github.com/invernyx/smartcars-3-public-api/assets/117974892/269407e1-8d5b-48fd-a945-5442688f3144)

### API Version

0.3.7

### PHP Version

5.7

### Database & version

Maria DB

### Webserver version

Apache win sql etc

### Browser

Chrome /EDGE latest

### Handler

phpvms5

### Additional context

please help us!!!

**Comment by GenericNerd** [comment] 2023-10-04 14:59
Is this a duplicate of #98?

**Closed as not planned** 2023-12-19 16:48 UTC
Labels: duplicate
